/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Mohammed Suboor' at '2/12/16 8:09 PM' with Gradle 2.9
 *
 * @author Mohammed Suboor, @date 2/12/16 8:09 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
